import{a as w,S,i as s}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const q="51317900-f0372c6e5a84e0989a980511e",b="https://pixabay.com/api/";async function f(o,r=1){try{const a={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await w.get(b,{params:a})).data}catch{throw new Error("Failed to fetch images")}}const d=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more");let v=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const r=o.map(e=>`
          <li class="gallery-item">
          <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          </a>
          <div class="info">
          <p>👍 ${e.likes}</p>
          <p>👁️ ${e.views}</p>
          <p>💬 ${e.comments}</p>
          <p>⬇️ ${e.downloads}</p>
          </div>
          </li>
          `).join("");d.insertAdjacentHTML("beforeend",r);const a=d.querySelectorAll("img"),n=Array.from(a).map(e=>new Promise(t=>{e.complete?t():(e.onload=()=>t(),e.onerror=()=>t())}));Promise.all(n).then(()=>{v.refresh(),m()})}function R(){d.innerHTML=""}function g(){p.classList.remove("hidden")}function m(){p.classList.add("hidden")}function B(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}const P=document.querySelector(".form"),$=document.querySelector(".load-more");document.querySelector(".gallery");let i="",l=1,u=0;P.addEventListener("submit",async o=>{if(o.preventDefault(),i=o.target.elements["search-text"].value.trim(),l=1,R(),L(),!i){s.warning({message:"Please enter a search term!",position:"topRight"});return}g();try{const r=await f(i,l);if(u=r.totalHits,r.hits.length===0){s.error({message:"No images found. Try a different query.",position:"topRight"});return}h(r.hits),u>15&&B()}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{m()}});$.addEventListener("click",async()=>{l+=1,g();try{const o=await f(i,l);h(o.hits);const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=u&&(L(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Failed to load more images.",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
